#!/usr/bin/env python3
"""Is the committed code map still the map of this tree?

WHY THIS EXISTS. `docs/knowledge/graph.json` is the structural half of the knowledge base --
the typed import graph plus the impact/orchestration centralities -- and `align` expands a
changed file into its blast-radius through it. It is generated by `.workflow/codemap.sh` and
it was generated by exactly two callers: `ingest` (once, at brownfield bootstrap) and
`/update`. NOTHING IN THE LOOP EVER REBUILT IT. So a greenfield project never had a map at
all, and a brownfield one had the map of its bootstrap commit for the rest of its life, while
the lens that reads it went on reporting a blast-radius of nothing and looking like a clean
answer. Measured on a real drive: ten source files written, zero nodes, no complaint anywhere.

WHAT IT DOES, and the one design choice that matters: it REGENERATES through the project's own
`codemap.sh` into a temp file and compares. It does NOT re-implement "which files are source".
A checker carrying its own notion of that would drift from the engine's the first time a
project passed `--exclude`, and would then report staleness that regenerating could not fix --
the worst kind of gate. Running the real wrapper means the comparison is always against what
the real generator would produce right now, which is the only question worth asking.

STRUCTURAL COMPARISON ONLY -- node paths and edges, never the centrality floats. Those are
deterministic given the same input, so they add nothing here, and comparing them would turn an
engine version bump into a staleness report whose remedy is not obvious from the message.

FAIL DIRECTION IS BLOCK, and it is affordable because the remedy is one command that takes
about a second. That is the whole reason this can be a gate rather than a warning: the cost of
being wrong is `bash .workflow/codemap.sh`, not an investigation.

WHAT IS NOT A FAILURE, stated so nobody has to discover it:
  * No `codemap.sh` -- a project that predates the runner, or one mid-bootstrap. Skip.
  * No source the engine recognizes -- a greenfield project before any code. A map of nothing
    is the correct map of nothing, and the absent file is not yet a defect.
  * The wrapper failing to run. That is a broken generator, not a stale map, and it is
    reported as its own thing: `undetermined`, which still blocks (an unrunnable generator is
    not a tree anybody should be committing on) but does not claim the map is stale.
"""
import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile

WRAPPER_REL = os.path.join(".workflow", "codemap.sh")
CONFIG_REL = os.path.join(".workflow", "config.json")


def _read_json(path):
    try:
        with open(path, encoding="utf-8") as fh:
            val = json.load(fh)
    except (OSError, ValueError):
        return None
    return val if isinstance(val, dict) else None


def graph_path(project_root):
    """Where the engine puts it by default -- resolved the same way the engine resolves it,
    from `project_root`, so the two cannot disagree about which file is the map."""
    cfg = _read_json(os.path.join(project_root, CONFIG_REL)) or {}
    proot = cfg.get("project_root") or "."
    return os.path.normpath(os.path.join(project_root, proot, "docs", "knowledge", "graph.json"))


def _shape(graph):
    """The structural identity of a map: its node paths and its edges. Order-independent."""
    if not isinstance(graph, dict):
        return None, None
    nodes = {n.get("path") for n in graph.get("nodes") or [] if isinstance(n, dict)}
    edges = set()
    for e in graph.get("edges") or []:
        if isinstance(e, dict):
            edges.add((e.get("from"), e.get("to"), e.get("kind")))
        elif isinstance(e, (list, tuple)):
            edges.add(tuple(e))
    return nodes, edges


def regenerate(project_root):
    """-> (graph, problem). Runs the project's OWN wrapper and reads what it produced.

    THE WRAPPER MAY OR MAY NOT ACCEPT ARGUMENTS, and that is not a hypothetical: `codemap.sh`
    is written out from a prose description at bootstrap, so its calling convention varies by
    who wrote it. Two trees built from the SAME package version were found to differ --
    `codemap.py ./project "$@"` in one, `codemap.py .` in the other -- so a gate that passed
    `--out` and trusted it would silently compare the map against ITSELF and report fresh
    forever. `--out` is still passed, because the wrappers that honour it stay untouched; the
    map is then BACKED UP AND RESTORED so the ones that ignore it are handled too.

    Restoring rather than keeping the regenerated map is deliberate. `graph.json` is committed,
    so rewriting it from inside a commit gate would stage a change nobody asked for. And the
    worst case if this is interrupted between the two -- the map is left FRESH -- is the state
    the fix produces anyway, so the unsafe direction here is not unsafe.
    """
    wrapper = os.path.join(project_root, WRAPPER_REL)
    out = graph_path(project_root)
    fd, tmp = tempfile.mkstemp(suffix=".graph.json")
    os.close(fd)
    os.remove(tmp)                       # a wrapper that honours --out creates it; absence is the signal
    backup = None
    if os.path.exists(out):
        fd2, backup = tempfile.mkstemp(suffix=".graph.bak")
        os.close(fd2)
        shutil.copy2(out, backup)
    try:
        run = subprocess.run(["bash", WRAPPER_REL, "--out", tmp],
                             cwd=project_root, capture_output=True, text=True, timeout=300)
        if run.returncode != 0:
            # An older wrapper `exec`s the engine with a fixed argv, so an unknown flag makes
            # argparse exit 2 having written nothing. Retry bare — the map it then writes in
            # place is what the backup is for.
            run = subprocess.run(["bash", WRAPPER_REL],
                                 cwd=project_root, capture_output=True, text=True, timeout=300)
        if run.returncode != 0:
            tail = (run.stderr or run.stdout or "").strip().splitlines()
            return None, "%s failed (%s)" % (WRAPPER_REL, tail[-1] if tail else "no output")
        fresh = _read_json(tmp) if os.path.exists(tmp) else _read_json(out)
        return fresh, None
    except subprocess.TimeoutExpired:
        return None, "%s did not finish within 300s" % WRAPPER_REL
    except OSError as exc:
        return None, "%s could not be run (%s)" % (wrapper, exc)
    finally:
        if backup is not None:
            try:
                shutil.copy2(backup, out)
            except OSError:
                pass
            try:
                os.remove(backup)
            except OSError:
                pass
        elif os.path.exists(out) and not os.path.exists(tmp):
            # There was no map before this ran and the wrapper wrote one in place. Leave the
            # tree as it was found; the verdict below is what tells the caller to build it.
            try:
                os.remove(out)
            except OSError:
                pass
        try:
            os.remove(tmp)
        except OSError:
            pass


def run(project_root):
    out = {"status": "clear", "detail": "", "missing": [], "extra": []}
    if not os.path.exists(os.path.join(project_root, WRAPPER_REL)):
        out["detail"] = "no %s — nothing generates a map in this project yet" % WRAPPER_REL
        return out

    fresh, problem = regenerate(project_root)
    if problem:
        out.update({"status": "undetermined", "detail": problem})
        return out

    fresh_nodes, fresh_edges = _shape(fresh)
    if not fresh_nodes:
        # The engine recognizes no source here. An absent or empty map is then correct.
        out["detail"] = "no source the code-map engine recognizes — an empty map is the right map"
        return out

    path = graph_path(project_root)
    have = _read_json(path)
    if have is None:
        out.update({"status": "stale",
                    "detail": "%s is missing or unreadable while the tree has %d mappable file(s)"
                              % (os.path.relpath(path, project_root), len(fresh_nodes)),
                    "missing": sorted(fresh_nodes)[:10]})
        return out

    have_nodes, have_edges = _shape(have)
    missing = sorted(fresh_nodes - have_nodes)
    extra = sorted(have_nodes - fresh_nodes)
    if missing or extra or fresh_edges != have_edges:
        bits = []
        if missing:
            bits.append("%d file(s) the map does not know about" % len(missing))
        if extra:
            bits.append("%d node(s) for files that are gone" % len(extra))
        if fresh_edges != have_edges:
            bits.append("the import edges have moved")
        out.update({"status": "stale", "detail": "; ".join(bits),
                    "missing": missing[:10], "extra": extra[:10]})
        return out

    out["detail"] = "%d node(s), %d edge(s) — matches the tree" % (len(have_nodes), len(have_edges))
    return out


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--project-root", default=".", help="where .workflow/ lives (default .)")
    ap.add_argument("--json", action="store_true", help="machine-readable verdict")
    args = ap.parse_args(argv)

    res = run(args.project_root)
    if args.json:
        json.dump(res, sys.stdout, indent=2)
        sys.stdout.write("\n")
    elif res["status"] == "clear":
        print("OK: code map — %s" % res["detail"])
    else:
        print("BLOCKED: code map is %s — %s" % (res["status"], res["detail"]), file=sys.stderr)
        for p in res["missing"]:
            print("  unmapped: %s" % p, file=sys.stderr)
        for p in res["extra"]:
            print("  stale node: %s" % p, file=sys.stderr)
        print("  fix: bash .workflow/codemap.sh", file=sys.stderr)
    return 0 if res["status"] == "clear" else 1


if __name__ == "__main__":
    sys.exit(main())
